version: "3.3"
services:
  emulator:
    image: emulator
    build: .
    privileged: true
    devices:
      - /dev/kvm
      - /dev/snd
    network_mode: host
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
